version: '2'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    image: frontend
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    image: backend
    command: npm start
    ports:
      - "5000:5000"